{
  // Notices
  NOTICE_SELECT_NODE_TO_COPY: "请选择要复制的节点。",
  NOTICE_MAP_CUT: "导图已剪切到剪贴板。",
  NOTICE_BRANCH_CUT: "分支已剪切到剪贴板。",
  NOTICE_MAP_COPIED: "导图已复制为 Markdown 格式。",
  NOTICE_BRANCH_COPIED: "分支已复制为列表格式。",
  NOTICE_CLIPBOARD_EMPTY: "剪贴板为空。",
  NOTICE_PASTE_ABORTED: "粘贴中止。剪贴板内容非 Markdown 列表或标题。",
  NOTICE_NO_LIST: "剪贴板中未发现有效的 Markdown 列表。",
  NOTICE_PASTE_START: "正在粘贴，请稍候，可能需要一些时间…",
  NOTICE_PASTE_COMPLETE: "粘贴完成。",
  NOTICE_ACTION_REQUIRES_ARROWS: "此操作需要方向键。仅可修改修饰键。",
  NOTICE_CONFLICT_WITH_ACTION: "与“{action}”操作冲突",
  NOTICE_OBSIDIAN_HOTKEY_CONFLICT: "⚠️ Obsidian 热键冲突！\n\n此按键将覆盖：\n“{command}”",
  NOTICE_GLOBAL_HOTKEY_CONFLICT: "⚠️ 全局热键冲突！\n\n此按键将覆盖：\n“{command}”",
  NOTICE_NO_HEADINGS: "链接文件中未发现小标题。",
  NOTICE_CANNOT_EDIT_MULTILINE: "无法直接编辑多行节点。\n请在 Excalidraw 中双击元素进行编辑，然后运行“自动重排导图”来更新布局。",
  NOTICE_CANNOT_MOVE_PINNED: "无法移动已锁定的节点。请先解锁。",
  NOTICE_CANNOT_MOVE_ROOT: "无法移动根节点。",
  NOTICE_CANNOT_PRMOTE_L1: "无法提升 1 级节点。",
  NOTICE_CANNOT_DEMOTE: "无法降级节点。没有可依附的前置同级节点。",
  NOTICE_SELECT_NODE_CONTAINING_LINK: "请选择包含链接的节点。",
  NOTICE_CANNOT_DEMOTE_NO_SIBLING_TO_ACCEPT: "无法降级：未找到可接收此节点的同级节点。",
  NOTICE_CANNOT_DEMOTE_NO_VALID_SIBLING: "无法降级：没有可附加的有效同级节点。",
  NOTICE_CANNOT_DEMOTE_CROSS_SIDE_NOT_ALLOWED: "无法降级：不允许跨侧降级。",
  NOTICE_CANNOT_MOVE_AUTO_LAYOUT_DISABLED: "禁用自动布局时无法移动节点。请先启用自动布局。",
  NOTICE_BRANCH_WIDTH_MANUAL_OVERRIDE: "分支粗细未更新，因为部分分支粗细已被手动修改。",
  NOTICE_CANNOT_CHANGE_MASTER_ROOT: "主根节点不能被转换。",
  NOTICE_SUBMAP_ROOT_ADDED: "已启用子图根节点。",
  NOTICE_SUBMAP_ROOT_REMOVED: "已移除子图根节点。其子节点将按亲代根节点布局重排。",
  CONFIRM_REMOVE_SUBMAP_ROOT: "恢复为普通节点吗？\n\n它将失去本地布局元数据，其子节点将按亲代根节点布局重排。",

  // Action labels (display only)
  ACTION_LABEL_ADD: "添加子节点",
  ACTION_LABEL_ADD_SIBLING_AFTER: "添加后置同级节点",
  ACTION_LABEL_ADD_SIBLING_BEFORE: "添加前置同级节点",
  ACTION_LABEL_ADD_FOLLOW: "添加 + 跟随",
  ACTION_LABEL_ADD_FOLLOW_FOCUS: "添加 + 跟随 + 聚焦",
  ACTION_LABEL_ADD_FOLLOW_ZOOM: "添加 + 跟随 + 缩放",
  ACTION_LABEL_SORT_ORDER: "更改顺序/提升节点",
  ACTION_LABEL_EDIT: "编辑节点",
  ACTION_LABEL_PIN: "锁定/解锁",
  ACTION_LABEL_BOX: "添加/移除边框",
  ACTION_LABEL_TOGGLE_GROUP: "编组/解除编组单分支",
  ACTION_LABEL_COPY: "复制",
  ACTION_LABEL_CUT: "剪切",
  ACTION_LABEL_PASTE: "粘贴",
  ACTION_LABEL_IMPORT_OUTLINE: "导入大纲",
  ACTION_LABEL_ZOOM: "循环缩放",
  ACTION_LABEL_FOCUS: "聚焦（并居中）节点",
  ACTION_LABEL_NAVIGATE: "导航",
  ACTION_LABEL_NAVIGATE_ZOOM: "导航 & 缩放",
  ACTION_LABEL_NAVIGATE_FOCUS: "导航 & 聚焦",
  ACTION_LABEL_FOLD: "折叠/展开分支",
  ACTION_LABEL_FOLD_L1: "折叠/展开 L1 子节点",
  ACTION_LABEL_FOLD_ALL: "递归折叠/展开分支",
  ACTION_LABEL_DOCK_UNDOCK: "停靠/取消停靠",
  ACTION_LABEL_HIDE: "停靠 & 隐藏",
  ACTION_LABEL_REARRANGE: "重排导图",
  ACTION_LABEL_TOGGLE_SUBMAP_ROOT: "开始/结束子图根节点",
  ACTION_LABEL_TOGGLE_CHECKBOX: "切换复选框状态",
  ACTION_LABEL_CALENDAR: "任务日历与优先级",
  ACTION_LABEL_TOGGLE_EMBED: "切换嵌入/链接",

  // Tooltips (shared)
  PIN_TOOLTIP_PINNED: "此元素已锁定。点击解锁所选元素的位置。",
  PIN_TOOLTIP_UNPINNED: "此元素未锁定。点击锁定所选元素的位置。",
  TOGGLE_GROUP_TOOLTIP_GROUP: "编组此分支。仅在“分支编组”禁用时可用。",
  TOGGLE_GROUP_TOOLTIP_UNGROUP: "解除编组此分支。仅在“分支编组”禁用时可用。",
  TOOLTIP_EDIT_NODE: "编辑所选节点的文本",
  TOOLTIP_PIN_INIT: "锁定/解锁节点位置。锁定的节点不会被自动重排。",
  TOOLTIP_REFRESH: "自动重排导图",
  TOOLTIP_DOCK: "停靠到侧边面板",
  TOOLTIP_UNDOCK: "转为浮动窗口",
  TOOLTIP_ZOOM_CYCLE: "循环切换元素缩放级别",
  TOOLTIP_TOGGLE_GROUP_BTN: "切换分支的编组状态。仅在“分支编组”禁用时可用。",
  TOOLTIP_TOGGLE_BOX: "切换节点边框",
  TOOLTIP_TOGGLE_BOUNDARY: "切换子树边界",
  TOOLTIP_TOGGLE_FLOATING_EXTRAS: "切换额外控件",
  TOOLTIP_CONFIGURE_PALETTE: "为分支配置自定义调色板",
  TOOLTIP_CONFIGURE_LAYOUT: "配置布局设置",
  TOOLTIP_MOVE_UP: "上移",
  TOOLTIP_MOVE_DOWN: "下移",
  TOOLTIP_EDIT_COLOR: "编辑",
  TOOLTIP_DELETE_COLOR: "删除",
  TOOLTIP_OPEN_PALETTE_PICKER: "打开颜色选择器",
  TOOLTIP_FOLD_BRANCH: "折叠/展开所选分支",
  TOOLTIP_FOLD_L1_BRANCH: "折叠/展开 L1 子节点",
  TOOLTIP_FOLD_ALL: "递归折叠/展开分支",
  TOOLTIP_IMPORT_OUTLINE: "从链接文件中导入小标题作为子节点数据",
  TOOLTIP_RESET_TO_DEFAULT: "恢复默认",
  TOOLTIP_SUBMAP_ROOT_ADD: "从所选节点开始子图",
  TOOLTIP_SUBMAP_ROOT_REMOVE: "将子图根节点恢复为普通节点",
  TOOLTIP_TOGGLE_CHECKBOX: "切换任务复选框状态",
  TOOLTIP_CALENDAR: "配置任务日期与优先级",
  TOOLTIP_TOGGLE_EMBED: "在嵌入和链接之间切换节点",

  // Buttons and labels
  DOCK_TITLE: "MindMap Builder",
  HELP_SUMMARY: "帮助",
  INPUT_PLACEHOLDER: "输入概念… 输入 [[ 插入链接",
  ONTOLOGY_PLACEHOLDER: "本体（箭头标签）",
  BUTTON_COPY: "复制",
  BUTTON_CUT: "剪切",
  BUTTON_PASTE: "粘贴",
  TITLE_ADD_SIBLING: `使用 ${ea.DEVICE.isMacOS || ea.DEVICE.isIOS ? "OPT" : "ALT"}+Enter 添加同级节点`,
  TITLE_ADD_FOLLOW: "添加并跟随",
  TITLE_COPY: "复制分支为文本",
  TITLE_CUT: "剪切分支为文本",
  TITLE_PASTE: "从剪贴板粘贴列表",
  LABEL_ZOOM_LEVEL: "缩放级别",
  LABEL_GROWTH_STRATEGY: "生长策略",
  LABEL_FILL_SWEEP: "填充扫过角度",
  DESC_FILL_SWEEP: "立即在整个“最大扫过角度”范围内分布节点，而不是随着节点数量增加逐渐扩大弧度。",
  LABEL_ARROW_TYPE: "曲线连接",
  LABEL_AUTO_LAYOUT: "自动布局",
  LABEL_GROUP_BRANCHES: "分支编组",
  LABEL_BOX_CHILD_NODES: "为子节点添加边框",
  LABEL_ROUNDED_CORNERS: "圆角",
  LABEL_USE_SCENE_STROKE: "使用场景线条样式",
  DESC_USE_SCENE_STROKE: "使用场景中最新的线条样式（实线、虚线、点线），否则分支将始终使用实线。",
  LABEL_BRANCH_SCALE: "分支粗细比例",
  LABEL_BASE_WIDTH: "基础粗细",
  LABEL_MULTICOLOR_BRANCHES: "多色分支",
  LABEL_MAX_WRAP_WIDTH: "最大折行宽度",
  LABEL_CENTER_TEXT: "文本居中",
  DESC_CENTER_TEXT: "关闭：根据位置左/右对齐；开启：文本强制居中。",
  LABEL_FONT_SIZES: "字体大小",
  HOTKEY_SECTION_TITLE: "热键配置",
  HOTKEY_HINT: "这些热键可能覆盖 Obsidian 默认设置。热键作用域默认为局部（⌨️），使用 🌐/🎨/⌨️ 切换作用域：🌐 Excalidraw 标签页可见即生效，🎨 Excalidraw 聚焦时生效，⌨️ 输入框聚焦时生效。",
  RECORD_HOTKEY_PROMPT: "按下热键…",
  ARIA_SCOPE_INPUT: "局部（Local）：仅在输入框聚焦时生效",
  ARIA_SCOPE_EXCALIDRAW: "Excalidraw：输入框或 Excalidraw 聚焦时生效",
  ARIA_SCOPE_GLOBAL: "全局（Global）：在 Obsidian 任何位置，Excalidraw 可见即生效",
  ARIA_RESTORE_DEFAULT: "恢复默认",
  ARIA_CUSTOMIZE_HOTKEY: "自定义此热键",
  ARIA_OVERRIDE_COMMAND: "将覆盖 Obsidian 命令：\n{command}",

  // Palette manager
  MODAL_PALETTE_TITLE: "导图分支调色板",
  LABEL_ENABLE_CUSTOM_PALETTE: "启用自定义调色板",
  DESC_ENABLE_CUSTOM_PALETTE: "使用以下颜色代替自动生成的颜色。",
  LABEL_RANDOMIZE_ORDER: "随机顺序",
  DESC_RANDOMIZE_ORDER: "随机选择颜色而非按顺序选择。",
  HEADING_ADD_NEW_COLOR: "添加新颜色",
  HEADING_EDIT_COLOR: "编辑颜色",
  LABEL_SELECT_COLOR: "选择颜色",
  BUTTON_CANCEL_EDIT: "取消编辑",
  BUTTON_ADD_COLOR: "添加颜色",
  BUTTON_UPDATE_COLOR: "更新颜色",

  // Layout configuration
  MODAL_LAYOUT_TITLE: "布局配置",
  // Section Headers
  SECTION_GENERAL: "常规间距",
  SECTION_RADIAL: "径向布局（顺时针）",
  SECTION_DIRECTIONAL: "定向布局（左/右）",
  SECTION_VERTICAL: "垂直导图（上/下）",
  SECTION_VISUALS: "视觉元素",
  SECTION_MANUAL: "手动模式行为",
  LAYOUT_RESET: "重置所有为默认值",
  LAYOUT_SAVE: "保存并关闭",
  // Radial Strings
  RADIAL_ASPECT_RATIO: "椭圆长宽比",
  DESC_RADIAL_ASPECT_RATIO: "控制形状。< 1.0 为瘦长（0.7 为纵向），1.0 为正圆，> 1.0 为宽扁（横向）。",
  RADIAL_POLE_GAP_BONUS: "极点间距补偿",
  DESC_RADIAL_POLE_GAP_BONUS: "增加椭圆南北两极区域内节点的间距。值越大，节点沿弧线推得越远。",
  RADIAL_START_ANGLE: "起始角度",
  DESC_RADIAL_START_ANGLE: "第一个节点出现的位置（度数）。270 为北，0 为东，90 为南。",
  RADIAL_MAX_SWEEP: "最大扫过角度",
  DESC_RADIAL_MAX_SWEEP: "分支可填充的弧范围。360 为全圆。较小的值会使圆不完整。",
  // Others
  GAP_X: "水平间距（Gap X）",
  DESC_LAYOUT_GAP_X: "亲代节点与子节点之间的水平距离。",
  GAP_Y: "垂直间距（Gap Y）",
  DESC_LAYOUT_GAP_Y: "同级节点之间的垂直距离。径向布局中的基础间距。",
  GAP_MULTIPLIER: "间距倍数",
  DESC_LAYOUT_GAP_MULTIPLIER: "叶节点（无子节点的节点）相对于字体大小的垂直间距。低：类似列表堆叠；高：标准树状间距。",
  DIRECTIONAL_ARC_SPAN_RADIANS: "定向张开弧度（Arc-span Radians）",
  DESC_LAYOUT_ARC_SPAN: "子节点排列的曲率。低（0.5）：较平，类似列表。高（2.0）：弯曲有机，但有重叠风险。",
  ROOT_RADIUS_FACTOR: "根节点半径系数",
  DESC_LAYOUT_ROOT_RADIUS: "相对于根节点边框的倍数，决定最初的半径。",
  MIN_RADIUS: "最小半径",
  DESC_LAYOUT_MIN_RADIUS: "从根节点中心到第一级节点的最小绝对距离。",
  RADIUS_PADDING_PER_NODE: "单节点径向空白边距",
  DESC_LAYOUT_RADIUS_PADDING: "每个子节点额外增加的半径，以适应密集型导图。",
  GAP_MULTIPLIER_RADIAL: "径向布局间距倍数",
  DESC_LAYOUT_GAP_RADIAL: "径向布局模式下的角度间距倍数。",
  GAP_MULTIPLIER_DIRECTIONAL: "垂直方向间距倍数",
  DESC_LAYOUT_GAP_DIRECTIONAL: "定向布局顶层分支之间的间距倍数。",
  INDICATOR_OFFSET: "折叠指示符偏移",
  DESC_LAYOUT_INDICATOR_OFFSET: "折叠指示符（三连点）距离节点的距离。",
  INDICATOR_OPACITY: "折叠指示符不透明度",
  DESC_LAYOUT_INDICATOR_OPACITY: "折叠指示符的不透明度（0-100）。",
  CONTAINER_PADDING: "容器内边距",
  DESC_LAYOUT_CONTAINER_PADDING: "使用边框样式时的内边距。",
  MAX_SEGMENT_LENGTH: "边界线精度",
  DESC_LAYOUT_BOUNDARY_LINE_PRECISION: "边界平滑精度。值越小越精细（30 = 精细），值越大越粗略（200 = 粗略）。",
  VERTICAL_SUBTREE_WIDTH_BLEND_SINGLE: "子树宽度参与度（单侧）",
  DESC_VERTICAL_SUBTREE_WIDTH_BLEND_SINGLE: "垂直导图中，单侧生长的子图占用（左/右）水平空间的强度。影响程度高。",
  VERTICAL_SUBTREE_WIDTH_BLEND_DUAL: "子树宽度参与度（双侧）",
  DESC_VERTICAL_SUBTREE_WIDTH_BLEND_DUAL: "垂直导图中，双侧生长的子图占用（左右）水平空间的强度。影响程度高。",
  VERTICAL_SUBTREE_SMOOTH_THRESHOLD_MULTIPLIER: "子树平滑压缩触发倍数",
  DESC_VERTICAL_SUBTREE_SMOOTH_THRESHOLD_MULTIPLIER: "超过 Gap Y 乘以该倍数后开始平滑压缩，避免新增子节点间距突变。通常在大导图中更明显。",
  VERTICAL_SUBTREE_SMOOTH_MIN_SCALE: "子树平滑压缩下限",
  DESC_VERTICAL_SUBTREE_SMOOTH_MIN_SCALE: "垂直子树宽度平滑压缩到的最小值。值越大越保留原宽度。通常在大导图中更明显。",
  HORIZONTAL_L1_SOFTCAP_THRESHOLD: "L1 水平方向软上限",
  DESC_HORIZONTAL_L1_SOFTCAP_THRESHOLD: "超过该 px 值后，上/下 L1 子树宽度开始压缩。对大导图影响程度中到高。",
  HORIZONTAL_L1_COMPRESSION_MIN_SCALE: "L1 水平方向压缩下限",
  DESC_HORIZONTAL_L1_COMPRESSION_MIN_SCALE: "上/下 L1 宽度压缩到的最小值。值越大越保留原宽度。软上限被达到（、开始压缩）后影响中等。",
  VERTICAL_COMPACT_PARENT_CHILD_GAP_RATIO: "紧凑亲子间距比例",
  DESC_VERTICAL_COMPACT_PARENT_CHILD_GAP_RATIO: "紧凑垂直子树中，亲子间距使用 Gap X 乘以该比例。极大影响视觉效果。",
  DIRECTIONAL_CROSS_AXIS_RATIO: "正交轴之比",
  DESC_DIRECTIONAL_CROSS_AXIS_RATIO: "与垂直于生长方向的轴（Cross-axis）的半径之比（0.2 = 扁，1.0 = 圆）。极大影响 L1 展开形态。",
  MANUAL_GAP_MULTIPLIER: "手动布局间距倍数",
  DESC_LAYOUT_MANUAL_GAP: "禁用自动布局时添加节点的间距倍数。",
  MANUAL_JITTER_RANGE: "手动布局抖动范围",
  DESC_LAYOUT_MANUAL_JITTER: "禁用自动布局时添加节点的随机位置偏移。",

  CALENDAR_DATE_INDEX: "第 {index} 个日期，共 {total} 个",
  CALENDAR_DATE_LABEL: "日期",
  CALENDAR_DATE_TYPE: "日期类型",
  CALENDAR_PRIORITY: "优先级",
  CALENDAR_RECURRENCE: "重复",
  CALENDAR_RECURRENCE_PLACEHOLDER: "every day",
  CALENDAR_RECURRENCE_DESC: "例如，'every day'，'every 2 weeks'<br><a href=\"https://publish.obsidian.md/tasks/Getting+Started/Recurring+Tasks\" target=\"_blank\" tabindex=\"-1\">Tasks 插件重复任务文档</a>",
  CALENDAR_INJECT_LINK: "插入节点链接",
  CALENDAR_INJECT_LINK_DESC: "在任务末尾添加指向该节点的链接。",
  CALENDAR_ALIAS_PLACEHOLDER: "别名",
  CALENDAR_BTN_CANCEL: "取消",
  CALENDAR_BTN_TASK_ONLY: "仅任务",
  CALENDAR_BTN_ADD_DATE_TASK: "添加日期和任务",

  CALENDAR_PRIORITY_HIGHEST: "最高",
  CALENDAR_PRIORITY_HIGH: "高",
  CALENDAR_PRIORITY_MEDIUM: "中",
  CALENDAR_PRIORITY_NORMAL: "普通",
  CALENDAR_PRIORITY_LOW: "低",
  CALENDAR_PRIORITY_LOWEST: "最低",

  CALENDAR_DATETYPE_DUE: "截止",
  CALENDAR_DATETYPE_START: "开始",
  CALENDAR_DATETYPE_SCHEDULED: "计划",
  CALENDAR_DATETYPE_CREATED: "创建",
  CALENDAR_DATETYPE_DONE: "完成",
  CALENDAR_DATETYPE_CANCELLED: "取消",

  // Presets
  PRESET_LABEL: "预设",
  PRESET_UNSAVED: "自定义 / 未关联",
  PRESET_BTN_SAVE: "保存预设",
  PRESET_BTN_DELETE: "删除预设",
  PRESET_BTN_NEW: "新建预设",
  PRESET_BTN_APPLY: "应用预设到导图",
  PRESET_WARNING_MODIFIED: "导图设置与预设不符。",
  PROMPT_NEW_PRESET_NAME: "新预设名称：",
  NOTICE_PRESET_DELETED: "预设已删除。",
  NOTICE_PRESET_SAVED: "预设已保存。",
  NOTICE_PRESET_APPLIED: "预设已应用。",

  // Misc
  INPUT_TITLE_PASTE_ROOT: "MindMap Builder 粘贴",
  INSTRUCTIONS: "> [!Tip]\n" +
    ">🚀 想要进阶？欢迎参加官方 [MindMap Builder 课程](https://www.visual-thinking-workshop.com/mindmap)！\n" +
    "\n" +
    "- **ENTER**：添加子节点并保留在当前亲代节点上，方便快速输入。" +
    "若输入框为空时按回车，焦点将移动到最新添加的子节点。" +
    "连续按回车将在该节点的同级节点间循环切换。\n" +
    "- **热键**：见侧边面板底部的配置选项。\n" +
    "- **停靠/取消停靠**：使用按钮或配置好的热键来切换输入框位置。\n" +
    "- **折叠**：仅在输入框停靠时显示按钮；取消停靠时请使用热键。\n" +
    "- **ESC**：将浮动输入框停靠，但不激活侧边面板。\n" +
    "- **着色**：顶层分支拥有独立颜色（多色模式），后代节点继承亲代颜色。\n" +
    "- **编组**：\n" +
    "  - 启用“分支编组”将递归地编组子树，从叶节点到顶层分支。\n" +
    "- **复制/粘贴**：导出/导入含缩进的 Markdown 列表。\n" +
    "\n" +
    "😍 如果你觉得这个脚本有用，欢迎 [请我喝杯咖啡 ☕](https://ko-fi.com/zsolt)。",
}
